import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/shared/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const InterSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-AR"
    suppressHydrationWarning>
      <body className={`${InterSans.variable} antialiased bg-slate-100 dark:bg-neutral-900`}>
        <ThemeProvider
          attribute={`class`}
          enableSystem
          defaultTheme={`system`}
        >
          {children}
          <Toaster position="top-right"/>
        </ThemeProvider>
      </body>
    </html>
  );
}
