import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/shared/components/theme-provider";

const InterSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-AR"
    suppressHydrationWarning>
      <body className={`${InterSans.variable} antialiased`}>
        <ThemeProvider
          attribute={`class`}
          enableSystem
          disableTransitionOnChange
          defaultTheme={`system`}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
